---
title: "simsDR"
output: html_document
date: '2023-07-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
results <- rbindlist(lapply(c(500, 1000, 1500, 2000, 2500), function(n) {
  out <- fread(paste0("simResultsDR/sim_results_DR_iter=1000_n=", n, "_pos=2.csv"))
  out$n <- n
  return(out)
}))
results
```


"\begin{tabular}{cc|cccc|ccc|ccc}
\toprule
\multirow{2}{*}{Dataset} & \multicolumn{5}{c|}{Bias} & \multicolumn{3}{c|}{RMSE} & \multicolumn{3}{c}{Coverage} \\
\cmidrule{2-12}
& & & auDRI & AIPW & & auDRI & AIPW & & auDRI & AIPW & \\


```{r}
datasets <- c("acic2018_1000", "acic2018_2500", "acic2018_5000", "acic2018_10000", "ihdp", "lalonde_cps", "lalonde_psid", "twins", "acic2017_17", "acic2017_18", "acic2017_19", "acic2017_20", "acic2017_21", "acic2017_22", "acic2017_23", "acic2017_24")

results_list <- lapply(datasets, function(data_name) {
  data <- fread(paste0("simResultsDR/sim_results_", data_name, "_xgboost.csv"))
  scale_bias <- scale_rmse <- mean(abs(data$ATE))
  data[, coverage := CI_left <= ATE & CI_right >= ATE]
  if(length(grep("acic2018", data_name)) > 0) {
    keep <- abs(data$estimate) <= 100 * max(abs(data$ATE) )
    max_range <- quantile((abs(data$estimate - data$ATE)/abs(data$ATE))[data$estimator == "AIPW"], c(0.95))
    keep <- findInterval((abs(data$estimate - data$ATE)/abs(data$ATE))[data$estimator == "AIPW"] , c(-1, max_range)) == 1
    keep <- rep(keep, each = 2)
    data <- data[which(keep),]
  }
 
  
  
  results <- unique(data[,
                         .( bias = abs(mean((estimate - ATE) )), 
                            rmse  = sqrt(mean((estimate/ATE - 1)^2)),
                            #bias = abs(weighted.mean(estimate - ATE, 1/stableATE )), 
                            #rmse  = sqrt(weighted.mean((estimate - ATE)^2, 1/stableATE^2)),
                            coverage = mean(coverage)), by = c( "misp",   "estimator", "lrnr")])
  results$bias <- results$bias  / scale_bias
  results$rmse <- results$rmse #/ scale_rmse
  results$bias <- format(signif(results$bias,3), scientific = FALSE)
  results$rmse <- format(signif(results$rmse,3), scientific = FALSE)
  results$coverage <-  format(signif(results$coverage,3), scientific = FALSE)
  results$data_name <- data_name
  # Scale for comparsion
  results_AIPW <- results[results$estimator == "AIPW", - c("estimator", "lrnr")]
  results_auDRI <- results[results$estimator == "auDRI",  - c("estimator", "lrnr")]
  col_names <-  c("bias", "rmse", "coverage")
  setnames(results_AIPW, col_names, paste0(col_names, "_AIPW"))
  setnames(results_auDRI, col_names, paste0(col_names, "_auDRI"))
  out <- cbind(results_AIPW, results_auDRI)
  out <- out[, !duplicated(colnames(out)), with = FALSE]
  setcolorder(out, c("misp", "data_name", 
                     "bias_auDRI", "bias_AIPW",
                     "rmse_auDRI", "rmse_AIPW",
                     "coverage_auDRI", "coverage_AIPW"))
  return(out)
})
results <- rbindlist(results_list, use.names = TRUE)

results_acic2018_1000 <- results[results$data_name == "acic2018_1000"]
results_acic2018_2500 <- results[results$data_name == "acic2018_2500"]
results_acic2018_5000 <- results[results$data_name == "acic2018_5000"]
results_acic2018_10000 <- results[results$data_name == "acic2018_10000"]
results_acic2018_aggregate <- copy(results_acic2018_1000)
results_acic2018_aggregate$data_name <- "acic2018_aggr"
for(colname in c("bias_auDRI", "bias_AIPW", "coverage_auDRI", "coverage_AIPW")) {
results_acic2018_aggregate[[colname]] <- (as.numeric(results_acic2018_1000[[colname]]) * sqrt(1000) + 
  as.numeric(results_acic2018_2500[[colname]]) * sqrt(2500) +
  as.numeric(results_acic2018_5000[[colname]]) * sqrt(5000) +
  as.numeric(results_acic2018_10000[[colname]] )* sqrt(10000) ) / sum(c(sqrt(1000), sqrt(2500), sqrt(5000) , sqrt(10000)  ))
results_acic2018_aggregate[[colname]] <- format(signif(results_acic2018_aggregate[[colname]] ,3), scientific = FALSE)
}
for(colname in c("rmse_auDRI", "rmse_AIPW")) {
results_acic2018_aggregate[[colname]] <- sqrt((as.numeric(results_acic2018_1000[[colname]])^2 * (1000) + 
  as.numeric(results_acic2018_2500[[colname]])^2 * (2500) +
  as.numeric(results_acic2018_5000[[colname]])^2 * (5000) +
  as.numeric(results_acic2018_10000[[colname]] )^2 * (10000) ) / sum(c((1000), (2500), (5000) , (10000)  )))
results_acic2018_aggregate[[colname]] <- format(signif(results_acic2018_aggregate[[colname]] ,3), scientific = FALSE)
}
 
  
results <- rbind(results,results_acic2018_aggregate )


setkeyv(results, c("misp", "data_name"))
results
results_1 <- copy(results[results$misp == 1])
results_1$misp <- NULL
library(kableExtra)
latex_code1 <- kable(results_1, "latex")

results_1 <- copy(results[results$misp == 2])
results_1$misp <- NULL
library(kableExtra)
latex_code2 <- kable(results_1, "latex")
cat(latex_code2)
cat(latex_code3)

results_1 <- copy(results)
library(kableExtra)
latex_code3 <- kable(results_1, "latex")

cat(latex_code3)
 
```


```{r}
library(ggplot2)
out <-  sim_results_ihdp_parametric
results <- as.data.table(out)
#keep <- !rep(abs(results$estimate[out$estimator == "auDRI"]) >= 100 * max(abs(results$ATE)) | abs(results$estimate[results$estimator == "AIPW"]) >= 100 * max(abs(results$ATE)), each = 2)
#results <- results[which(keep),]

# results$ATE <-ATE
results[, coverage := CI_left <= ATE & CI_right >= ATE]


results <- unique(results[,
                          .( bias = abs(mean((estimate - ATE) )), 
                             rmse  = sqrt(mean((estimate - ATE)^2)),
                             coverage = mean(coverage)), by = c( "misp",   "estimator", "lrnr")])
results$bias <- results$bias / mean(abs(out$ATE))
results$rmse <- results$rmse / mean(abs(out$ATE))
results <- results[results$misp !=4, ]
results



```





```{r}
library(data.table)
out <- sim_results_DR_iter_1000_n_2500_pos_2
results <- as.data.table(out)
ATE <- mean(results$ATE)
results$ATE <-ATE
results[, coverage := CI_left <= ATE & CI_right >= ATE]
results[, sd := abs(CI_left -CI_right)/1.96/2]


results <- unique(results[, .(sd = mean(sd), se = sd(estimate-ATE), bias = abs(mean(estimate - ATE)), coverage = mean(coverage)), by = c( "misp",   "estimator", "lrnr")])
results[, rmse := sqrt(bias^2 + se^2)]

results$rmse <- results$rmse /abs(ATE)
results$se <- results$se /abs(ATE)
results$sd <- results$sd /abs(ATE)
results$bias <- results$bias /abs(ATE)
results <- results[results$misp !=4, ]
results
results[results$lrnr=="all"]


```

Do table

For each lrnr.
n  Treatment Outcome Both
mse (coverage)


```{r}
results[results$lrnr=="xgboost",]

```

```{r}
library(data.table)

n_list <- c(  1000, 1500, 2000, 2500)

results <-
  rbindlist(lapply(n_list, function(n){
    try({
      key <- paste0("DR_iter=", "1000", "_n=", n, "_pos=2")
      data <- fread(paste0("./simResultsDR/sim_results_", key, ".csv"))
      key <- paste0("DR_iter=", "2000", "_n=", n, "_pos=2")
      try({ data <- fread(paste0("./simResultsDR/sim_results_", key, ".csv"))})
      return(data)
    })
    return(data.table())
  }))



ATE <- mean(results$ATE)
results$ATE <-ATE
results[, coverage := CI_left <= ATE & CI_right >= ATE]
results[, sd := abs(CI_left -CI_right)/1.96/2]


results <- unique(results[, .(sd = mean(sd), se = sd(estimate-ATE), bias = abs(mean(estimate - ATE)), coverage = mean(coverage)), by = c( "misp",   "estimator", "lrnr", "n", "pos_const")])
results[, rmse := sqrt(bias^2 + se^2)]
relative_results <- unique(copy(results)[,-c("estimator"), with = FALSE])
keep_index <- which(results$estimator == "auDRI")
relative_results <- data.table(bias = results$bias[results$estimator == "auDRI"] / results$bias[results$estimator == "AIPW"], rmse = results$rmse[results$estimator == "auDRI"] / results$rmse[results$estimator == "AIPW"] )
relative_results <- cbind(results[keep_index, c("misp", "lrnr", "n")], relative_results)

relative_results

library(ggplot2)
w <- 7
h <- 5
results$misp <- c("Both", "Treatment", "Outcome" )[match(results$misp, c("1", "2", "3" ))]
relative_results$misp <- c("Both", "Treatment", "Outcome" )[match(relative_results$misp, c("1", "2", "3" ))]

for(lrnr in c("all")) {
  for(misp in c("Both", "Treatment", "Outcome" )) {
    #relative_results_sub$lrnr == lrnr &
    results_sub <- as.data.frame(results)
    relative_results_sub <- as.data.frame(relative_results)
    results_sub <- results_sub[  results_sub$misp == misp,]
    relative_results_sub <- relative_results_sub[  relative_results_sub$misp == misp,]
    
    
    p <-  ggplot(relative_results_sub, aes(x= n, y = bias, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed")   + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
    )  + labs(x = "Sample Size (n)", y = "Bias", color = "Estimator", group = "Estimator", shape= "Estimator") 
    
    ggsave(   filename = paste0("DR=", pos_const,lrnr,misp, "Bias.pdf") , width = w, height = h)
    
    
    
    p <-  ggplot(relative_results_sub, aes(x= n, y = rmse, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed")   + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
    )  + labs(x = "Sample Size (n)", y = "RMSE", color = "Estimator", group = "Estimator", shape= "Estimator") 
    ggsave(filename = paste0("DR=", pos_const,lrnr,misp, "MSE.pdf"), width = w, height = h)
    
    p <- ggplot(results_sub, aes(x= n, y = coverage, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed")  + facet_wrap(~estimator, ncol =2)+ scale_y_continuous(limits = c(min(results_sub$coverage), 0.97)) + geom_hline(yintercept = 0.95, color = "grey") + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
    )  + labs(x = "Sample Size (n)", y = "CI Coverage", color = "Estimator", group = "Estimator", shape= "Estimator")  
    
    
    ggsave(filename = paste0("DR=", pos_const,lrnr,misp, "CI.pdf"), width = w, height = h)
  }
}


```

```{r}
library(ggplot2)
w <- 7
h <- 5
results$misp <- c("Both", "Treatment", "Outcome" )[match(results$misp, c("1", "2", "3" ))]

for(lrnr in c("all")) {
  for(misp in c("Both", "Treatment", "Outcome" )) {
    tmp <- results
    tmp <- as.data.frame(tmp)[tmp$lrnr == lrnr,]
    tmp <- as.data.frame(tmp)[tmp$misp == misp,]
    
    
    #maxval <- 3*min(tmp$rmse[tmp$n ==500])
    maxval <- max(tmp$rmse )
    tmp$bias <- pmin(tmp$bias, maxval)
    tmp$se <- pmin(tmp$se, maxval)
    tmp$mse <- pmin(tmp$rmse, maxval)
    
    limits <- c(0, maxval + .01)
    p <-  ggplot(tmp, aes(x= n, y = bias, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed") +  facet_wrap(~estimator, ncol =2)  + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
    )  + labs(x = "Sample Size (n)", y = "Bias", color = "Estimator", group = "Estimator", shape= "Estimator") +  scale_y_continuous( limits = limits) 
    
    ggsave(   filename = paste0("DR=", pos_const,lrnr,misp, "Bias.pdf") , width = w, height = h)
    
    
    
    
    
    
    ggplot(tmp, aes(x= n, y = se, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed")  + facet_wrap(~estimator, ncol =2) + theme_bw()  +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
    )  + labs(x = "Sample Size (n)", y = "Standard Error", color = "Estimator", group = "Estimator", shape= "Estimator") +  scale_y_continuous( limits = limits)
    
    ggsave(filename = paste0("DR=", pos_const,lrnr,misp, "SE.pdf"), width = w, height = h)
    
    
    ggplot(tmp, aes(x= n, y = mse, color = lrnr, shape= lrnr)) + geom_point(size = 4)  + geom_line( color="grey", linetype = "dashed") + facet_wrap(~estimator, ncol =2) + theme_bw()  +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
    )  + labs(x = "Sample Size (n)", y = "Root Mean Square Error", color = "Estimator", group = "Estimator", shape= "Estimator")  +  scale_y_continuous( limits = limits)
    
    ggsave(filename = paste0("DR=", pos_const,lrnr,misp, "MSE.pdf"), width = w, height = h)
    
    p <- ggplot(tmp, aes(x= n, y = coverage, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed")  + facet_wrap(~estimator, ncol =2)+ scale_y_continuous(limits = c(min(tmp$coverage), 0.97)) + geom_hline(yintercept = 0.95, color = "grey") + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
    )  + labs(x = "Sample Size (n)", y = "CI Coverage", color = "Estimator", group = "Estimator", shape= "Estimator")  
    
    
    ggsave(filename = paste0("DR=", pos_const,lrnr,misp, "CI.pdf"), width = w, height = h)
  }
}


p <- ggplot(tmp, aes(x= n, y = coverage, color = lrnr, shape= lrnr)) + geom_point(size = 4) + facet_wrap(~estimator, ncol =2)+ scale_y_log10() + geom_hline(yintercept = 0.95, color = "grey") + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" , legend.title = element_blank()
)  + labs(x = "Sample Size (n)", y = "CI Coverage", color = "estimator", group = "estimator", shape= "estimator")  


```



```{r}

results[n >= 1000 & pos == 4e-02]

```
